name: credcommerce

on:
  workflow_dispatch:
  # schedule:
    # - cron: "15 6 * * *"  # 06:15 UTC (adjust)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas gspread google-auth

      - name: Run extraction for all cities
        env:
          CRED_COMM_ACC_JSON: ${{ secrets.CRED_COMM_ACC_JSON }}
          CDL_ACC_JSON: ${{ secrets.CDL_ACC_JSON }}
          GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          WORKSHEET_NAME: dados_cred_commerce
        run: |
          python scripts/credcommerce/credcom_sg.py
          python scripts/credcommerce/cdl.py

      - name: Download trier file
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: python scripts/credcommerce/trier_credcom_all.py

      - name: Upload trier file
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: python scripts/credcommerce/proc_trier_credcom_all.py
        
      - name: Update TRIERxCREDCOM sheet
        env:
          GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python scripts/credcommerce/comb_trier_credcom_all.py
        
