name: minerva daily update

on:
  workflow_dispatch: 
  #schedule:
    #- cron: '0 6 * * *'  # Runs every day at 3am GMT-3

permissions: write-all # Give the workflow permission to write to the repository

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl xlrd numpy gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client packaging
      
      #- name: download trier/alegrete file 
        #env:
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
        #run: python scripts/minerva/trier_alegrete.py
        
      - name: download trier/sg file 
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: python scripts/minerva/trier_sg.py

      - name: process trier/sg file 
        env:
          GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python scripts/minerva/proc_trier_sg.py 

      #- name: download minerva/alegrete file 
        #env:
          #minerva_username: ${{ secrets.MINERVA_USERNAME }}
          #minerva_password: ${{ secrets.MINERVA_PASSWORD }}
        #run: python scripts/minerva/epays_alegrete.py

      #- name: download minerva/sg file 
        #env:
          #minerva_username: ${{ secrets.MINERVA_USERNAME }}
          #minerva_password: ${{ secrets.MINERVA_PASSWORD }}
        #run: python scripts/minerva/epays_sg.py
