name: sindsaude daily update

on:
  workflow_dispatch: 
  #schedule:
    #- cron: '0 6 * * *'  # Runs every day at 3am GMT-3

permissions: write-all # Give the workflow permission to write to the repository

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl xlrd numpy gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client packaging
      
      #- name: download trier file 
        #env:
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
        #run: python scripts/sindsaude/trier.py

      #- name: process trier file
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: python scripts/sindsaude/proc_trier.py 

      - name: download bgcard file
        env:
          FL1: ${{ secrets.FL1 }}
          FL2: ${{ secrets.FL2 }}
          bgcard_password: ${{ secrets.BGCARD_PASSWORD }}
          bgcard_num: ${{ secrets.BGCARD_NUM }}
        run: python scripts/sindsaude/bgcard.py

      - name: process bgcard file
        env:
          GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python scripts/sindsaude/proc_bgcard.py 
        
      #- name: download trier/sg file 
        #env:
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
        #run: python scripts/minerva/trier_sg.py

      #- name: process trier/sg file 
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: python scripts/minerva/proc_trier_sg.py 

      #- name: download minerva/alegrete file 
        #env:
          #minerva_username: ${{ secrets.MINERVA_USERNAME }}
          #minerva_password: ${{ secrets.MINERVA_PASSWORD }}
        #run: python scripts/minerva/epays_alegrete.py

      #- name: process minerva/alegrete file 
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: python scripts/minerva/proc_minerva_alegrete.py 

      #- name: download minerva/sg file 
        #env:
          #minerva_username: ${{ secrets.MINERVA_USERNAME }}
          #minerva_password: ${{ secrets.MINERVA_PASSWORD }}
        #run: python scripts/minerva/epays_sg.py

      #- name: process minerva/sg file 
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: python scripts/minerva/proc_minerva_sg.py 

      #- name: Upload data to spreadsheet
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: |
          #python scripts/minerva/comb_trier_minerva_sg.py

      #- name: Upload data to spreadsheet
        #env:
          #GSERVICE_JSON: ${{ secrets.GSERVICE_JSON }}
          #SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: |
          #python scripts/minerva/comb_trier_minerva_alegrete.py
